// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPKun-efBqPDT9elUBj5f7ywy9Wv1AJU',
    appId: '1:839379308722:web:8a42cc02edd737ebb279ab',
    messagingSenderId: '839379308722',
    projectId: 'minimal-social-app-7da08',
    authDomain: 'minimal-social-app-7da08.firebaseapp.com',
    storageBucket: 'minimal-social-app-7da08.firebasestorage.app',
    measurementId: 'G-FRDJTRQE0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyamISFBoO1TmW086WerZAkm6HudV9EQ',
    appId: '1:839379308722:android:f1cdd8fa95c3117db279ab',
    messagingSenderId: '839379308722',
    projectId: 'minimal-social-app-7da08',
    storageBucket: 'minimal-social-app-7da08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_zQk2NIhF9xc1M51vtmeNyrBfaySi4I',
    appId: '1:839379308722:ios:bbec6d51282adad7b279ab',
    messagingSenderId: '839379308722',
    projectId: 'minimal-social-app-7da08',
    storageBucket: 'minimal-social-app-7da08.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_zQk2NIhF9xc1M51vtmeNyrBfaySi4I',
    appId: '1:839379308722:ios:bbec6d51282adad7b279ab',
    messagingSenderId: '839379308722',
    projectId: 'minimal-social-app-7da08',
    storageBucket: 'minimal-social-app-7da08.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKPKun-efBqPDT9elUBj5f7ywy9Wv1AJU',
    appId: '1:839379308722:web:b4e3e4d22fe32597b279ab',
    messagingSenderId: '839379308722',
    projectId: 'minimal-social-app-7da08',
    authDomain: 'minimal-social-app-7da08.firebaseapp.com',
    storageBucket: 'minimal-social-app-7da08.firebasestorage.app',
    measurementId: 'G-YGWWJNWYW7',
  );
}
